/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import controlMySql.MySqlConn;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class AltasTriple extends javax.swing.JInternalFrame {

    MySqlConn conn;
    private String habitacion;
    /**
     * Creates new form NewJInternalFrame
     */
    public AltasTriple() {
        conn = new MySqlConn();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHabitacion101 = new javax.swing.JLabel();
        jLabelHabitacion103 = new javax.swing.JLabel();
        jLabelHabitacion110 = new javax.swing.JLabel();
        jLabelHabitacion105 = new javax.swing.JLabel();
        jLabelHabitacion104 = new javax.swing.JLabel();
        jLabelHabitacion113 = new javax.swing.JLabel();
        jLabelHabitacion114 = new javax.swing.JLabel();
        jLabelHabitacion100 = new javax.swing.JLabel();
        jLabelHabitacion102 = new javax.swing.JLabel();
        jLabelHabitacion112 = new javax.swing.JLabel();
        jLabelHabitacion111 = new javax.swing.JLabel();
        jLabelHabitacion109 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButtonHabitacion106 = new javax.swing.JButton();
        jButtonHabitacion107 = new javax.swing.JButton();
        jButtonHabitacion108 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelHabitacion119 = new javax.swing.JLabel();
        jLabelHabitacion117 = new javax.swing.JLabel();
        jLabelHabitacion126 = new javax.swing.JLabel();
        jLabelHabitacion123 = new javax.swing.JLabel();
        jLabelHabitacion118 = new javax.swing.JLabel();
        jLabelHabitacion125 = new javax.swing.JLabel();
        jLabelHabitacion121 = new javax.swing.JLabel();
        jLabelHabitacion115 = new javax.swing.JLabel();
        jLabelHabitacion129 = new javax.swing.JLabel();
        jLabelHabitacion122 = new javax.swing.JLabel();
        jLabelHabitacion127 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButtonHabitacion116 = new javax.swing.JButton();
        jButtonHabitacion120 = new javax.swing.JButton();
        jButtonHabitacion124 = new javax.swing.JButton();
        jButtonHabitacion128 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Habitaciones");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelHabitacion101.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion101.setText("101");
        jLabelHabitacion101.setEnabled(false);
        jLabelHabitacion101.setOpaque(true);
        jLabelHabitacion101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHabitacion101MouseClicked(evt);
            }
        });

        jLabelHabitacion103.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion103.setText("103");
        jLabelHabitacion103.setEnabled(false);
        jLabelHabitacion103.setOpaque(true);

        jLabelHabitacion110.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion110.setText("110");
        jLabelHabitacion110.setEnabled(false);
        jLabelHabitacion110.setOpaque(true);

        jLabelHabitacion105.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion105.setText("105");
        jLabelHabitacion105.setEnabled(false);
        jLabelHabitacion105.setOpaque(true);

        jLabelHabitacion104.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion104.setText("104");
        jLabelHabitacion104.setEnabled(false);
        jLabelHabitacion104.setOpaque(true);

        jLabelHabitacion113.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion113.setText("113");
        jLabelHabitacion113.setEnabled(false);
        jLabelHabitacion113.setOpaque(true);

        jLabelHabitacion114.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion114.setText("114");
        jLabelHabitacion114.setEnabled(false);
        jLabelHabitacion114.setOpaque(true);

        jLabelHabitacion100.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion100.setText("100");
        jLabelHabitacion100.setEnabled(false);
        jLabelHabitacion100.setOpaque(true);
        jLabelHabitacion100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHabitacion100MouseClicked(evt);
            }
        });

        jLabelHabitacion102.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion102.setText("102");
        jLabelHabitacion102.setEnabled(false);
        jLabelHabitacion102.setOpaque(true);
        jLabelHabitacion102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHabitacion102MouseClicked(evt);
            }
        });

        jLabelHabitacion112.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion112.setText("112");
        jLabelHabitacion112.setEnabled(false);
        jLabelHabitacion112.setOpaque(true);

        jLabelHabitacion111.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion111.setText("111");
        jLabelHabitacion111.setEnabled(false);
        jLabelHabitacion111.setOpaque(true);

        jLabelHabitacion109.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion109.setText("109");
        jLabelHabitacion109.setEnabled(false);
        jLabelHabitacion109.setOpaque(true);

        jLabel31.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Primer Piso");

        jButtonHabitacion106.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion106.setText("106");
        jButtonHabitacion106.setBorderPainted(false);
        jButtonHabitacion106.setContentAreaFilled(false);
        jButtonHabitacion106.setOpaque(true);
        jButtonHabitacion106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion106ActionPerformed(evt);
            }
        });

        jButtonHabitacion107.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion107.setText("107");
        jButtonHabitacion107.setBorderPainted(false);
        jButtonHabitacion107.setContentAreaFilled(false);
        jButtonHabitacion107.setOpaque(true);
        jButtonHabitacion107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion107ActionPerformed(evt);
            }
        });

        jButtonHabitacion108.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion108.setText("108");
        jButtonHabitacion108.setBorderPainted(false);
        jButtonHabitacion108.setContentAreaFilled(false);
        jButtonHabitacion108.setOpaque(true);
        jButtonHabitacion108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion108ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion102, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion101, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion100, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion103, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHabitacion104, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHabitacion105, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHabitacion106, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHabitacion107, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion114, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion113, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonHabitacion108, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion109, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion111, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion110, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion112, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHabitacion101, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion100, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion113, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion114, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion112, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion102, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHabitacion103, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion111, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelHabitacion105, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelHabitacion109, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelHabitacion104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHabitacion110, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHabitacion106, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion107, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion108, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabelHabitacion119.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion119.setText("119");
        jLabelHabitacion119.setEnabled(false);
        jLabelHabitacion119.setOpaque(true);

        jLabelHabitacion117.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion117.setText("117");
        jLabelHabitacion117.setEnabled(false);
        jLabelHabitacion117.setOpaque(true);

        jLabelHabitacion126.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion126.setText("126");
        jLabelHabitacion126.setEnabled(false);
        jLabelHabitacion126.setOpaque(true);

        jLabelHabitacion123.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion123.setText("123");
        jLabelHabitacion123.setEnabled(false);
        jLabelHabitacion123.setOpaque(true);

        jLabelHabitacion118.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion118.setText("118");
        jLabelHabitacion118.setEnabled(false);
        jLabelHabitacion118.setOpaque(true);

        jLabelHabitacion125.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion125.setText("125");
        jLabelHabitacion125.setEnabled(false);
        jLabelHabitacion125.setOpaque(true);

        jLabelHabitacion121.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion121.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion121.setText("121");
        jLabelHabitacion121.setEnabled(false);
        jLabelHabitacion121.setOpaque(true);

        jLabelHabitacion115.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion115.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion115.setText("115");
        jLabelHabitacion115.setEnabled(false);
        jLabelHabitacion115.setOpaque(true);

        jLabelHabitacion129.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion129.setText("129");
        jLabelHabitacion129.setEnabled(false);
        jLabelHabitacion129.setOpaque(true);

        jLabelHabitacion122.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion122.setText("122");
        jLabelHabitacion122.setEnabled(false);
        jLabelHabitacion122.setOpaque(true);

        jLabelHabitacion127.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion127.setText("127");
        jLabelHabitacion127.setEnabled(false);
        jLabelHabitacion127.setOpaque(true);

        jLabel47.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Segundo Piso");

        jButtonHabitacion116.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion116.setText("116");
        jButtonHabitacion116.setBorderPainted(false);
        jButtonHabitacion116.setContentAreaFilled(false);
        jButtonHabitacion116.setOpaque(true);
        jButtonHabitacion116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion116ActionPerformed(evt);
            }
        });

        jButtonHabitacion120.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion120.setText("120");
        jButtonHabitacion120.setBorderPainted(false);
        jButtonHabitacion120.setContentAreaFilled(false);
        jButtonHabitacion120.setOpaque(true);
        jButtonHabitacion120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion120ActionPerformed(evt);
            }
        });

        jButtonHabitacion124.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion124.setText("124");
        jButtonHabitacion124.setBorderPainted(false);
        jButtonHabitacion124.setContentAreaFilled(false);
        jButtonHabitacion124.setOpaque(true);
        jButtonHabitacion124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion124ActionPerformed(evt);
            }
        });

        jButtonHabitacion128.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion128.setText("128");
        jButtonHabitacion128.setBorderPainted(false);
        jButtonHabitacion128.setContentAreaFilled(false);
        jButtonHabitacion128.setOpaque(true);
        jButtonHabitacion128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion128ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonHabitacion116, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelHabitacion115, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHabitacion129, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion128, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion117, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion118, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion127, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion126, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion119, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion120, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelHabitacion121, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion122, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion123, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButtonHabitacion124, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion125, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHabitacion115, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion129, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion116, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion128, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHabitacion127, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabelHabitacion117, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHabitacion126, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHabitacion118, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHabitacion119, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHabitacion121, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion125, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion122, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion123, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion120, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion124, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHabitacion100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacion100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHabitacion100MouseClicked

    private void jLabelHabitacion101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacion101MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHabitacion101MouseClicked

    private void jLabelHabitacion102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacion102MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelHabitacion102MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String query = "Select habitacion from registros";
        int i = 0;
        this.conn.Consult(query);
        try{
            this.conn.rs.last();
            i=this.conn.rs.getRow();
        }catch(SQLException ex){
        }
        if(i == 30)
            JOptionPane.showMessageDialog(this, "El hotel se encuetran lleno!");
        
        String aux;
        query =  "Select habitacion from registros where tipoHabitacion = 'Triple'";
        
        this.conn.Consult(query);
        try{
            do{
                aux = this.conn.rs.getString(1);
                if(aux.equals(this.jButtonHabitacion106.getText().trim())){
                    this.jButtonHabitacion106.setBackground(Color.RED);
                    this.jButtonHabitacion106.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion107.getText().trim())){
                    this.jButtonHabitacion107.setBackground(Color.RED);
                    this.jButtonHabitacion107.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion108.getText().trim())){
                    this.jButtonHabitacion108.setBackground(Color.RED);
                    this.jButtonHabitacion108.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion116.getText().trim())){
                    this.jButtonHabitacion116.setBackground(Color.RED);
                    this.jButtonHabitacion116.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion120.getText().trim())){
                    this.jButtonHabitacion120.setBackground(Color.RED);
                    this.jButtonHabitacion120.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion124.getText().trim())){
                    this.jButtonHabitacion124.setBackground(Color.RED);
                    this.jButtonHabitacion124.setEnabled(false);
                } else if(aux.equals(this.jButtonHabitacion128.getText().trim())){
                    this.jButtonHabitacion128.setBackground(Color.RED);
                    this.jButtonHabitacion128.setEnabled(false);
                } 
                
            }while(this.conn.rs.next());
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonHabitacion106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion106ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion106.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion106ActionPerformed

    private void jButtonHabitacion107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion107ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion107.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion107ActionPerformed

    private void jButtonHabitacion108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion108ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion108.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion108ActionPerformed

    private void jButtonHabitacion116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion116ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion116.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion116ActionPerformed

    private void jButtonHabitacion120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion120ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion120.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion120ActionPerformed

    private void jButtonHabitacion124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion124ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion124.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion124ActionPerformed

    private void jButtonHabitacion128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion128ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion128.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Triple",3,1600);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion128ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHabitacion106;
    private javax.swing.JButton jButtonHabitacion107;
    private javax.swing.JButton jButtonHabitacion108;
    private javax.swing.JButton jButtonHabitacion116;
    private javax.swing.JButton jButtonHabitacion120;
    private javax.swing.JButton jButtonHabitacion124;
    private javax.swing.JButton jButtonHabitacion128;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabelHabitacion100;
    private javax.swing.JLabel jLabelHabitacion101;
    private javax.swing.JLabel jLabelHabitacion102;
    private javax.swing.JLabel jLabelHabitacion103;
    private javax.swing.JLabel jLabelHabitacion104;
    private javax.swing.JLabel jLabelHabitacion105;
    private javax.swing.JLabel jLabelHabitacion109;
    private javax.swing.JLabel jLabelHabitacion110;
    private javax.swing.JLabel jLabelHabitacion111;
    private javax.swing.JLabel jLabelHabitacion112;
    private javax.swing.JLabel jLabelHabitacion113;
    private javax.swing.JLabel jLabelHabitacion114;
    private javax.swing.JLabel jLabelHabitacion115;
    private javax.swing.JLabel jLabelHabitacion117;
    private javax.swing.JLabel jLabelHabitacion118;
    private javax.swing.JLabel jLabelHabitacion119;
    private javax.swing.JLabel jLabelHabitacion121;
    private javax.swing.JLabel jLabelHabitacion122;
    private javax.swing.JLabel jLabelHabitacion123;
    private javax.swing.JLabel jLabelHabitacion125;
    private javax.swing.JLabel jLabelHabitacion126;
    private javax.swing.JLabel jLabelHabitacion127;
    private javax.swing.JLabel jLabelHabitacion129;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
