/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import controlMySql.MySqlConn;
import java.awt.Color;
import java.sql.SQLException;


public class AltasSencillas extends javax.swing.JInternalFrame {

    
    MySqlConn conn;
    private String habitacion;
    /**
     * Creates new form NewJInternalFrame
     */
    public AltasSencillas() {
        conn = new MySqlConn();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHabitacion101 = new javax.swing.JLabel();
        jLabelHabitacion110 = new javax.swing.JLabel();
        jLabelHabitacion107 = new javax.swing.JLabel();
        jLabelHabitacion106 = new javax.swing.JLabel();
        jLabelHabitacion104 = new javax.swing.JLabel();
        jLabelHabitacion113 = new javax.swing.JLabel();
        jLabelHabitacion108 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButtonHabitacion100 = new javax.swing.JButton();
        jButtonHabitacion102 = new javax.swing.JButton();
        jButtonHabitacion103 = new javax.swing.JButton();
        jButtonHabitacion105 = new javax.swing.JButton();
        jButtonHabitacion109 = new javax.swing.JButton();
        jButtonHabitacion111 = new javax.swing.JButton();
        jButtonHabitacion112 = new javax.swing.JButton();
        jButtonHabitacion114 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelHabitacion119 = new javax.swing.JLabel();
        jLabelHabitacion117 = new javax.swing.JLabel();
        jLabelHabitacion126 = new javax.swing.JLabel();
        jLabelHabitacion120 = new javax.swing.JLabel();
        jLabelHabitacion116 = new javax.swing.JLabel();
        jLabelHabitacion118 = new javax.swing.JLabel();
        jLabelHabitacion125 = new javax.swing.JLabel();
        jLabelHabitacion124 = new javax.swing.JLabel();
        jLabelHabitacion127 = new javax.swing.JLabel();
        jLabelHabitacion128 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButtonHabitacion115 = new javax.swing.JButton();
        jButtonHabitacion121 = new javax.swing.JButton();
        jButtonHabitacion122 = new javax.swing.JButton();
        jButtonHabitacion123 = new javax.swing.JButton();
        jButtonHabitacion129 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Habitaciones");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelHabitacion101.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion101.setText("101");
        jLabelHabitacion101.setEnabled(false);
        jLabelHabitacion101.setOpaque(true);
        jLabelHabitacion101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHabitacion101MouseClicked(evt);
            }
        });

        jLabelHabitacion110.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion110.setText("110");
        jLabelHabitacion110.setEnabled(false);
        jLabelHabitacion110.setOpaque(true);

        jLabelHabitacion107.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion107.setText("107");
        jLabelHabitacion107.setEnabled(false);
        jLabelHabitacion107.setOpaque(true);

        jLabelHabitacion106.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion106.setText("106");
        jLabelHabitacion106.setEnabled(false);
        jLabelHabitacion106.setOpaque(true);

        jLabelHabitacion104.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion104.setText("104");
        jLabelHabitacion104.setEnabled(false);
        jLabelHabitacion104.setOpaque(true);

        jLabelHabitacion113.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion113.setText("113");
        jLabelHabitacion113.setEnabled(false);
        jLabelHabitacion113.setOpaque(true);

        jLabelHabitacion108.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion108.setText("108");
        jLabelHabitacion108.setEnabled(false);
        jLabelHabitacion108.setOpaque(true);

        jLabel31.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Primer Piso");

        jButtonHabitacion100.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion100.setText("100");
        jButtonHabitacion100.setBorderPainted(false);
        jButtonHabitacion100.setContentAreaFilled(false);
        jButtonHabitacion100.setOpaque(true);
        jButtonHabitacion100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion100ActionPerformed(evt);
            }
        });

        jButtonHabitacion102.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion102.setText("102");
        jButtonHabitacion102.setBorderPainted(false);
        jButtonHabitacion102.setContentAreaFilled(false);
        jButtonHabitacion102.setOpaque(true);
        jButtonHabitacion102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion102ActionPerformed(evt);
            }
        });

        jButtonHabitacion103.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion103.setText("103");
        jButtonHabitacion103.setBorderPainted(false);
        jButtonHabitacion103.setContentAreaFilled(false);
        jButtonHabitacion103.setOpaque(true);
        jButtonHabitacion103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion103ActionPerformed(evt);
            }
        });

        jButtonHabitacion105.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion105.setText("105");
        jButtonHabitacion105.setBorderPainted(false);
        jButtonHabitacion105.setContentAreaFilled(false);
        jButtonHabitacion105.setOpaque(true);
        jButtonHabitacion105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion105ActionPerformed(evt);
            }
        });

        jButtonHabitacion109.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion109.setText("109");
        jButtonHabitacion109.setBorderPainted(false);
        jButtonHabitacion109.setContentAreaFilled(false);
        jButtonHabitacion109.setOpaque(true);
        jButtonHabitacion109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion109ActionPerformed(evt);
            }
        });

        jButtonHabitacion111.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion111.setText("111");
        jButtonHabitacion111.setBorderPainted(false);
        jButtonHabitacion111.setContentAreaFilled(false);
        jButtonHabitacion111.setOpaque(true);
        jButtonHabitacion111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion111ActionPerformed(evt);
            }
        });

        jButtonHabitacion112.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion112.setText("112");
        jButtonHabitacion112.setBorderPainted(false);
        jButtonHabitacion112.setContentAreaFilled(false);
        jButtonHabitacion112.setOpaque(true);
        jButtonHabitacion112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion112ActionPerformed(evt);
            }
        });

        jButtonHabitacion114.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion114.setText("114");
        jButtonHabitacion114.setBorderPainted(false);
        jButtonHabitacion114.setContentAreaFilled(false);
        jButtonHabitacion114.setOpaque(true);
        jButtonHabitacion114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion114ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion101, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion100, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHabitacion104, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHabitacion105, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHabitacion106, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelHabitacion107, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonHabitacion102, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion103, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonHabitacion114, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion113, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion108, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion109, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion110, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion111, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion112, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHabitacion101, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion113, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion100, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion114, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHabitacion102, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHabitacion112, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHabitacion103, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHabitacion111, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHabitacion106, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion107, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion108, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion105, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHabitacion109, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelHabitacion104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion110, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabelHabitacion119.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion119.setText("119");
        jLabelHabitacion119.setEnabled(false);
        jLabelHabitacion119.setOpaque(true);

        jLabelHabitacion117.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion117.setText("117");
        jLabelHabitacion117.setEnabled(false);
        jLabelHabitacion117.setOpaque(true);

        jLabelHabitacion126.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion126.setText("126");
        jLabelHabitacion126.setEnabled(false);
        jLabelHabitacion126.setOpaque(true);

        jLabelHabitacion120.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion120.setText("120");
        jLabelHabitacion120.setEnabled(false);
        jLabelHabitacion120.setOpaque(true);

        jLabelHabitacion116.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion116.setText("116");
        jLabelHabitacion116.setEnabled(false);
        jLabelHabitacion116.setOpaque(true);

        jLabelHabitacion118.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion118.setText("118");
        jLabelHabitacion118.setEnabled(false);
        jLabelHabitacion118.setOpaque(true);

        jLabelHabitacion125.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion125.setText("125");
        jLabelHabitacion125.setEnabled(false);
        jLabelHabitacion125.setOpaque(true);

        jLabelHabitacion124.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion124.setText("124");
        jLabelHabitacion124.setEnabled(false);
        jLabelHabitacion124.setOpaque(true);

        jLabelHabitacion127.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion127.setText("127");
        jLabelHabitacion127.setEnabled(false);
        jLabelHabitacion127.setOpaque(true);

        jLabelHabitacion128.setBackground(new java.awt.Color(255, 255, 204));
        jLabelHabitacion128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitacion128.setText("128");
        jLabelHabitacion128.setEnabled(false);
        jLabelHabitacion128.setOpaque(true);

        jLabel47.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Segundo Piso");

        jButtonHabitacion115.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion115.setText("115");
        jButtonHabitacion115.setBorderPainted(false);
        jButtonHabitacion115.setContentAreaFilled(false);
        jButtonHabitacion115.setOpaque(true);
        jButtonHabitacion115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion115ActionPerformed(evt);
            }
        });

        jButtonHabitacion121.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion121.setText("121");
        jButtonHabitacion121.setBorderPainted(false);
        jButtonHabitacion121.setContentAreaFilled(false);
        jButtonHabitacion121.setOpaque(true);
        jButtonHabitacion121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion121ActionPerformed(evt);
            }
        });

        jButtonHabitacion122.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion122.setText("122");
        jButtonHabitacion122.setBorderPainted(false);
        jButtonHabitacion122.setContentAreaFilled(false);
        jButtonHabitacion122.setOpaque(true);
        jButtonHabitacion122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion122ActionPerformed(evt);
            }
        });

        jButtonHabitacion123.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion123.setText("123");
        jButtonHabitacion123.setBorderPainted(false);
        jButtonHabitacion123.setContentAreaFilled(false);
        jButtonHabitacion123.setOpaque(true);
        jButtonHabitacion123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion123ActionPerformed(evt);
            }
        });

        jButtonHabitacion129.setBackground(new java.awt.Color(204, 204, 255));
        jButtonHabitacion129.setText("129");
        jButtonHabitacion129.setBorderPainted(false);
        jButtonHabitacion129.setContentAreaFilled(false);
        jButtonHabitacion129.setOpaque(true);
        jButtonHabitacion129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitacion129ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion116, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion115, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47)
                        .addGap(114, 114, 114)
                        .addComponent(jButtonHabitacion129, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion128, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion117, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion118, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabitacion127, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitacion126, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelHabitacion119, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion120, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion121, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion122, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHabitacion123, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelHabitacion124, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHabitacion125, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHabitacion116, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHabitacion128, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion115, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHabitacion129, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHabitacion127, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabelHabitacion117, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabitacion118, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHabitacion126, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHabitacion120, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHabitacion119, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHabitacion125, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHabitacion124, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHabitacion121, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHabitacion122, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHabitacion123, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHabitacion101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHabitacion101MouseClicked

    }//GEN-LAST:event_jLabelHabitacion101MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        String aux;
        String query = "Select habitacion from registros where tipoHabitacion = 'Sencilla'";
        
        this.conn.Consult(query);
        try{
            do{
                aux = this.conn.rs.getString(1);
                if(aux.equals(this.jButtonHabitacion100.getText())){
                    this.jButtonHabitacion100.setBackground(Color.RED);
                    this.jButtonHabitacion100.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion102.getText())){
                    this.jButtonHabitacion102.setBackground(Color.RED);
                    this.jButtonHabitacion102.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion103.getText())){
                    this.jButtonHabitacion103.setBackground(Color.RED);
                    this.jButtonHabitacion103.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion105.getText())){
                    this.jButtonHabitacion105.setBackground(Color.RED);
                    this.jButtonHabitacion105.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion109.getText())){
                    this.jButtonHabitacion109.setBackground(Color.RED);
                    this.jButtonHabitacion109.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion111.getText())){
                    this.jButtonHabitacion111.setBackground(Color.RED);
                    this.jButtonHabitacion111.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion112.getText())){
                    this.jButtonHabitacion112.setBackground(Color.RED);
                    this.jButtonHabitacion112.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion114.getText())){
                    this.jButtonHabitacion114.setBackground(Color.RED);
                    this.jButtonHabitacion114.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion115.getText())){
                    this.jButtonHabitacion115.setBackground(Color.RED);
                    this.jButtonHabitacion115.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion121.getText())){
                    this.jButtonHabitacion121.setBackground(Color.RED);
                    this.jButtonHabitacion121.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion122.getText())){
                    this.jButtonHabitacion122.setBackground(Color.RED);
                    this.jButtonHabitacion122.setEnabled(false);
                } 
                else if(aux.equals(this.jButtonHabitacion123.getText())){
                    this.jButtonHabitacion123.setBackground(Color.RED);
                    this.jButtonHabitacion123.setEnabled(false);
                }
                else if(aux.equals(this.jButtonHabitacion129.getText())){
                    this.jButtonHabitacion129.setBackground(Color.RED);
                    this.jButtonHabitacion129.setEnabled(false);
                } 
                
            }while(this.conn.rs.next());
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonHabitacion100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion100ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion100.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion100ActionPerformed

    private void jButtonHabitacion102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion102ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion102.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion102ActionPerformed

    private void jButtonHabitacion103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion103ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion103.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion103ActionPerformed

    private void jButtonHabitacion105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion105ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion105.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion105ActionPerformed

    private void jButtonHabitacion109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion109ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion109.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion109ActionPerformed

    private void jButtonHabitacion111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion111ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion111.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion111ActionPerformed

    private void jButtonHabitacion112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion112ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion112.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion112ActionPerformed

    private void jButtonHabitacion114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion114ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion114.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion114ActionPerformed

    private void jButtonHabitacion115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion115ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion115.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion115ActionPerformed

    private void jButtonHabitacion121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion121ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion121.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion121ActionPerformed

    private void jButtonHabitacion122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion122ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion122.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion122ActionPerformed

    private void jButtonHabitacion123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion123ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion123.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion123ActionPerformed

    private void jButtonHabitacion129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitacion129ActionPerformed
        // TODO add your handling code here:
        habitacion = this.jButtonHabitacion129.getText().trim();
        RegistrarDatos registrar = new RegistrarDatos(habitacion, "Sencilla",1);
        Menu.jDesktopPaneEscritorio.add(registrar);
        registrar.toFront();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHabitacion129ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHabitacion100;
    private javax.swing.JButton jButtonHabitacion102;
    private javax.swing.JButton jButtonHabitacion103;
    private javax.swing.JButton jButtonHabitacion105;
    private javax.swing.JButton jButtonHabitacion109;
    private javax.swing.JButton jButtonHabitacion111;
    private javax.swing.JButton jButtonHabitacion112;
    private javax.swing.JButton jButtonHabitacion114;
    private javax.swing.JButton jButtonHabitacion115;
    private javax.swing.JButton jButtonHabitacion121;
    private javax.swing.JButton jButtonHabitacion122;
    private javax.swing.JButton jButtonHabitacion123;
    private javax.swing.JButton jButtonHabitacion129;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabelHabitacion101;
    private javax.swing.JLabel jLabelHabitacion104;
    private javax.swing.JLabel jLabelHabitacion106;
    private javax.swing.JLabel jLabelHabitacion107;
    private javax.swing.JLabel jLabelHabitacion108;
    private javax.swing.JLabel jLabelHabitacion110;
    private javax.swing.JLabel jLabelHabitacion113;
    private javax.swing.JLabel jLabelHabitacion116;
    private javax.swing.JLabel jLabelHabitacion117;
    private javax.swing.JLabel jLabelHabitacion118;
    private javax.swing.JLabel jLabelHabitacion119;
    private javax.swing.JLabel jLabelHabitacion120;
    private javax.swing.JLabel jLabelHabitacion124;
    private javax.swing.JLabel jLabelHabitacion125;
    private javax.swing.JLabel jLabelHabitacion126;
    private javax.swing.JLabel jLabelHabitacion127;
    private javax.swing.JLabel jLabelHabitacion128;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
