
package proyecto;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAltas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSencilla = new javax.swing.JMenuItem();
        jMenuItemDoble = new javax.swing.JMenuItem();
        jMenuItemTriple = new javax.swing.JMenuItem();
        jMenuBajas = new javax.swing.JMenu();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemFotos = new javax.swing.JMenuItem();
        jMenuItemIngresos = new javax.swing.JMenuItem();
        jMenuItemOcupacionHab = new javax.swing.JMenuItem();
        jMenuItemHabitaciones = new javax.swing.JMenuItem();
        jMenuItemOcupacionHotel = new javax.swing.JMenuItem();
        jMenuItemCostoHabitacion = new javax.swing.JMenuItem();
        jMenuItemUbicacionHuesped = new javax.swing.JMenuItem();
        jMenuItemEstadoHabitacion = new javax.swing.JMenuItem();
        jMenuItemHabitacionesPiso = new javax.swing.JMenuItem();
        jMenuItemListaHuespedes = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jMenuAltas.setText("Registro");
        jMenuAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltasActionPerformed(evt);
            }
        });

        jMenu1.setText("Tipo de Habitacion");

        jMenuItemSencilla.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSencilla.setText("Sencilla");
        jMenuItemSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSencillaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSencilla);

        jMenuItemDoble.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDoble.setText("Doble");
        jMenuItemDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDobleActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDoble);

        jMenuItemTriple.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTriple.setText("Triple");
        jMenuItemTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTripleActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTriple);

        jMenuAltas.add(jMenu1);

        jMenuBar1.add(jMenuAltas);

        jMenuBajas.setText("Salida");
        jMenuBajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBajasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuBajas);

        jMenuConsultas.setText("Consultas");

        jMenuItemFotos.setText("Fotos del hotel");
        jMenuItemFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFotosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemFotos);

        jMenuItemIngresos.setText("Ingresos del hotel");
        jMenuItemIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemIngresos);

        jMenuItemOcupacionHab.setText("Ocupacion por habitacion");
        jMenuConsultas.add(jMenuItemOcupacionHab);

        jMenuItemHabitaciones.setText("Habitaciones del hotel ");
        jMenuConsultas.add(jMenuItemHabitaciones);

        jMenuItemOcupacionHotel.setText("Ocupacion del hotel");
        jMenuConsultas.add(jMenuItemOcupacionHotel);

        jMenuItemCostoHabitacion.setText("Costo de las habitaciones");
        jMenuConsultas.add(jMenuItemCostoHabitacion);

        jMenuItemUbicacionHuesped.setText("Ubiacion de un huesped");
        jMenuConsultas.add(jMenuItemUbicacionHuesped);

        jMenuItemEstadoHabitacion.setText("Estado de una habitacion");
        jMenuConsultas.add(jMenuItemEstadoHabitacion);

        jMenuItemHabitacionesPiso.setText("Habitaciones por piso");
        jMenuConsultas.add(jMenuItemHabitacionesPiso);

        jMenuItemListaHuespedes.setText("Lista de huespedes");
        jMenuConsultas.add(jMenuItemListaHuespedes);

        jMenuBar1.add(jMenuConsultas);

        jMenuSalir.setText("Salir");
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltasActionPerformed
        
        
    }//GEN-LAST:event_jMenuAltasActionPerformed

    private void jMenuItemSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSencillaActionPerformed
        // TODO add your handling code here:
        AltasSencillas altas = new AltasSencillas();
        this.jDesktopPaneEscritorio.add(altas);
        altas.show();
    }//GEN-LAST:event_jMenuItemSencillaActionPerformed

    private void jMenuItemTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTripleActionPerformed
        // TODO add your handling code here:
        AltasTriple altas = new AltasTriple();
        this.jDesktopPaneEscritorio.add(altas);
        altas.show();
    }//GEN-LAST:event_jMenuItemTripleActionPerformed

    private void jMenuItemDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDobleActionPerformed
        // TODO add your handling code here:
        AltasDobles altas = new AltasDobles();
        this.jDesktopPaneEscritorio.add(altas);
        altas.show();
    }//GEN-LAST:event_jMenuItemDobleActionPerformed

    private void jMenuBajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBajasMouseClicked
        // TODO add your handling code here:
        Salida bajas = new Salida();
        this.jDesktopPaneEscritorio.add(bajas);
        bajas.show();
    }//GEN-LAST:event_jMenuBajasMouseClicked

    private void jMenuItemFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFotosActionPerformed
        // TODO add your handling code here:
        Consulta1 fotos= new Consulta1();
        this.jDesktopPaneEscritorio.add(fotos);
        fotos.show();
    }//GEN-LAST:event_jMenuItemFotosActionPerformed

    private void jMenuItemIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresosActionPerformed
        // TODO add your handling code here:
        Consulta2 ingresos= new Consulta2();
        this.jDesktopPaneEscritorio.add(ingresos);
        ingresos.show();
    }//GEN-LAST:event_jMenuItemIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAltas;
    private javax.swing.JMenu jMenuBajas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemCostoHabitacion;
    private javax.swing.JMenuItem jMenuItemDoble;
    private javax.swing.JMenuItem jMenuItemEstadoHabitacion;
    private javax.swing.JMenuItem jMenuItemFotos;
    private javax.swing.JMenuItem jMenuItemHabitaciones;
    private javax.swing.JMenuItem jMenuItemHabitacionesPiso;
    private javax.swing.JMenuItem jMenuItemIngresos;
    private javax.swing.JMenuItem jMenuItemListaHuespedes;
    private javax.swing.JMenuItem jMenuItemOcupacionHab;
    private javax.swing.JMenuItem jMenuItemOcupacionHotel;
    private javax.swing.JMenuItem jMenuItemSencilla;
    private javax.swing.JMenuItem jMenuItemTriple;
    private javax.swing.JMenuItem jMenuItemUbicacionHuesped;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
