/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import controlMySql.MySqlConn;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author Adrian
 */
public class Salida extends javax.swing.JInternalFrame {

    MySqlConn conn;
    private String nombre, ciudad, fechaIn, fechaSa, tipoHab, numHab; 
    private int  dias, total = 0, totalS, costo; 
    /**
     * Creates new form Salida
     */
    public Salida() {
        conn = new MySqlConn();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonComprobar = new javax.swing.JButton();
        jTextFieldHabitacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTipoHab = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxServCuarto = new javax.swing.JCheckBox();
        jCheckBoxServBar = new javax.swing.JCheckBox();
        jCheckBoxServTinto = new javax.swing.JCheckBox();
        jCheckBoxServSpa = new javax.swing.JCheckBox();
        jCheckBoxServNiñera = new javax.swing.JCheckBox();
        jCheckBoxServBuffet = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMontoPagar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Salidas");

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        jLabel1.setText("Habitacion:");

        jLabel2.setText("Nombre: ");

        jTextFieldNombre.setEditable(false);

        jTextFieldTipoHab.setEditable(false);

        jLabel3.setText("Tipo de Habitacion:");

        jLabel4.setText("Servicios Extra:");

        jCheckBoxServCuarto.setText("Servicio al cuarto");

        jCheckBoxServBar.setText("Servicio de bar");

        jCheckBoxServTinto.setText("Servicio de tintoreria");

        jCheckBoxServSpa.setText("Servicio de SPA");

        jCheckBoxServNiñera.setText("Servicio de niñera");

        jCheckBoxServBuffet.setText("Servicio de buffet");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto a pagar:");

        jButton1.setText("Marcar Salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxServCuarto)
                            .addComponent(jCheckBoxServBar)
                            .addComponent(jCheckBoxServNiñera))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxServBuffet)
                            .addComponent(jCheckBoxServSpa)
                            .addComponent(jCheckBoxServTinto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldHabitacion)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTipoHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonComprobar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonComprobar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxServCuarto)
                    .addComponent(jCheckBoxServTinto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxServBar)
                    .addComponent(jCheckBoxServSpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxServNiñera)
                    .addComponent(jCheckBoxServBuffet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
        // TODO add your handling code here:
        String query = "Select * from registros where habitacion = '" + this.jTextFieldHabitacion.getText().trim() + "'";
        
        this.conn.Consult(query);
        try{
            this.jTextFieldNombre.setText(this.conn.rs.getString(6));
            this.jTextFieldTipoHab.setText(this.conn.rs.getString(2));
            this.costo = this.conn.rs.getInt(3);
            this.ciudad = this.conn.rs.getString(7);
            this.fechaIn= this.conn.rs.getString(8);
            this.fechaSa = this.conn.rs.getString(9);
            this.nombre = this.jTextFieldNombre.getText().trim();
            this.tipoHab = this.jTextFieldTipoHab.getText().trim();
            this.numHab = this.jTextFieldHabitacion.getText().trim();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "No se encontro la habitacion");
        }
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:

        
        if(this.jCheckBoxServCuarto.isSelected())
            total += 250;
        if(this.jCheckBoxServBar.isSelected())
            total += 800;
        if(this.jCheckBoxServNiñera.isSelected())
            total += 700;
        if(this.jCheckBoxServTinto.isSelected())
            total += 180;
        if(this.jCheckBoxServSpa.isSelected())
            total += 600;
        if(this.jCheckBoxServBuffet.isSelected())
            total += 300;
        
       
        try {
           int ex = this.conn.rs.getInt(5);
           if( ex > 0 )
            total += (ex * 200);
        } catch (SQLException ex1) {
        }
        
        
        
        String query2 = "Select TIMESTAMPDIFF(day,(Select fechaEntrada from registros where habitacion = '"+ this.jTextFieldHabitacion.getText().trim() + "'), (Select fechaSalida from registros where habitacion = '"+ this.jTextFieldHabitacion.getText().trim() + "')) ";
        
        this.conn.Consult(query2);
        
        
        
        try {
            dias = this.conn.rs.getInt(1);
        } catch (SQLException ex1) {
        }
        
        if("Sencilla".equals(this.tipoHab)){
            total += (dias*800);
            totalS = (dias*800);
        }else if("Doble".equals(this.tipoHab)){
            total += (dias*1200);
            totalS = (dias*1200);
        }else if("Triple".equals(this.tipoHab)){
            total += (dias*1600);
            totalS = (dias*1600);
        }
        
        
        this.jTextFieldMontoPagar.setText(total+"");
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String query = "insert into ingresos VALUES ( id ,'" + this.jTextFieldMontoPagar.getText().trim() + "')";
        this.conn.Update(query);
        query = "delete from registros where habitacion = " + this.jTextFieldHabitacion.getText().trim();
        this.conn.Update(query);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JCheckBox jCheckBoxServBar;
    private javax.swing.JCheckBox jCheckBoxServBuffet;
    private javax.swing.JCheckBox jCheckBoxServCuarto;
    private javax.swing.JCheckBox jCheckBoxServNiñera;
    private javax.swing.JCheckBox jCheckBoxServSpa;
    private javax.swing.JCheckBox jCheckBoxServTinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldHabitacion;
    private javax.swing.JTextField jTextFieldMontoPagar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTipoHab;
    // End of variables declaration//GEN-END:variables
}
