/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.ImageIcon;

/**
 *
 * @author Adrian
 */
public class Voucher extends javax.swing.JInternalFrame {
    
    private String nombre, ciudad, fechaIn, fechaSa, tipoHab, numHab; 
    private int  ocuMax, totOcu, perEx; 
    
    /**
     * Creates new form Voucher
     */
    public Voucher() {
        initComponents();
    }

    public Voucher(String nombre, String ciudad, String fechaIn, String fechaSa, String tipoHab, String numHab, int ocuMax, int totOcu, int perEx) {
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.fechaIn = fechaIn;
        this.fechaSa = fechaSa;
        this.tipoHab = tipoHab;
        this.numHab = numHab;
        this.ocuMax = ocuMax;
        this.totOcu = totOcu;
        this.perEx = perEx;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelFechaSa = new javax.swing.JLabel();
        jLabelFechaIn = new javax.swing.JLabel();
        jLabelNumHabitacion = new javax.swing.JLabel();
        jLabelPiso = new javax.swing.JLabel();
        jLabelLimHuespedes = new javax.swing.JLabel();
        jLabelTipoHab = new javax.swing.JLabel();
        jLabelTotOcupantes = new javax.swing.JLabel();
        jLabelReg = new javax.swing.JLabel();
        jLabelPerEx = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelHotel = new javax.swing.JLabel();
        jLabelLema = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vouncher");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNombre.setText("jLabel1");

        jLabelCiudad.setText("jLabel1");

        jLabelFechaSa.setText("jLabel1");

        jLabelFechaIn.setText("jLabel1");

        jLabelNumHabitacion.setText("jLabel1");

        jLabelPiso.setText("jLabel1");

        jLabelLimHuespedes.setText("jLabel1");

        jLabelTipoHab.setText("jLabel1");

        jLabelTotOcupantes.setText("jLabel1");

        jLabelReg.setText("Registro Completado!");

        jLabelPerEx.setText("jLabel3");

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelHotel.setText("jLabel1");

        jLabelLema.setText("jLabel1");

        jLabelDireccion.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCiudad)
                            .addComponent(jLabelFechaIn)
                            .addComponent(jLabelFechaSa)
                            .addComponent(jLabelTotOcupantes)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumHabitacion)
                                    .addComponent(jLabelTipoHab))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLimHuespedes)
                                    .addComponent(jLabelPiso)))
                            .addComponent(jLabelReg)
                            .addComponent(jLabelPerEx)
                            .addComponent(jLabelHotel)
                            .addComponent(jLabelLema)
                            .addComponent(jLabelDireccion))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelHotel)
                .addGap(18, 18, 18)
                .addComponent(jLabelLema)
                .addGap(18, 18, 18)
                .addComponent(jLabelDireccion)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre)
                .addGap(18, 18, 18)
                .addComponent(jLabelCiudad)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaIn)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaSa)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumHabitacion)
                    .addComponent(jLabelPiso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoHab)
                    .addComponent(jLabelLimHuespedes))
                .addGap(18, 18, 18)
                .addComponent(jLabelTotOcupantes)
                .addGap(18, 18, 18)
                .addComponent(jLabelPerEx)
                .addGap(18, 18, 18)
                .addComponent(jLabelReg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.jLabelImagen.setIcon(new ImageIcon("src/imagenes/gowa.jpg"));
        this.jLabelHotel.setText("GOWA Hotel");
        this.jLabelLema.setText("Sueños pesados, costos ligeros");
        this.jLabelDireccion.setText("Blvd. Kukulcan Km 7.5, Punta Cancun, 77500 Cancún, Q.R.");
        this.jLabelNombre.setText("Nombre del huésped: " + this.nombre);
        this.jLabelCiudad.setText("Ciudad de origen: " + this.ciudad);
        this.jLabelFechaIn.setText("Fecha de ingreso: " + this.fechaIn);
        this.jLabelFechaSa.setText("Fecha de salida : " + this.fechaSa);
        this.jLabelNumHabitacion.setText("Numero de habitación: " + this.numHab);
        int aux = Integer.parseInt(this.numHab);
        if((aux > 99) && (aux < 115))
            this.jLabelPiso.setText("Piso: 1");
        else
            this.jLabelPiso.setText("Piso: 2");
        
        this.jLabelTipoHab.setText("Tipo de habitación: " + this.tipoHab);
        this.jLabelLimHuespedes.setText("Limite: " + this.ocuMax + " huespedes");
        this.jLabelTotOcupantes.setText("Total de ocupantes de la habitación: " + this.totOcu);
        this.jLabelPerEx.setText("Personas extra: " + this.perEx);
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaIn;
    private javax.swing.JLabel jLabelFechaSa;
    private javax.swing.JLabel jLabelHotel;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelLema;
    private javax.swing.JLabel jLabelLimHuespedes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumHabitacion;
    private javax.swing.JLabel jLabelPerEx;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelReg;
    private javax.swing.JLabel jLabelTipoHab;
    private javax.swing.JLabel jLabelTotOcupantes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
